### ISSUE TITLE
UI : URL option input mixed up with Local File Source Kind

### ISSUE THREAD

**Issue by pcadeot** [LandscapeCombinator/LandscapeCombinator#6]
From Landscape Spawner BP, when selecting HMap SourceKind to "URL", the URL input won't show ;
It shows when selecting the HMap SourceKind to "Local File" (below the contextually correct "Local File Path" input) : 
![image](https://github.com/LandscapeCombinator/LandscapeCombinator/assets/50657616/d717d99f-c6e0-42e8-a93c-b5f24015a80c)
(from main branch, as of 29/10/2023 07:45 download, Paris time)

**Comment by LandscapeCombinator** [comment]
Thanks a lot for the report, it should be good now. I also added a direct source for RGE ALTI REUNION, so you won't have to play with the URL manually anymore. I should have done this a while ago!

**Comment by LandscapeCombinator** [comment]
I also added a `LandscapeSpawner` example called: `BP_LandscapeSpawner_PitonDeLaFournaise_1k`

**Comment by pcadeot** [comment]
> I also added a `LandscapeSpawner` example called: `BP_LandscapeSpawner_PitonDeLaFournaise_1k`

Thanks, I'm looking forward to try these :)
